const Customerdata = [
    {
        id:1,
        Product:"Women Pink Floral Printed",
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    },
    {
        id:2,
        Product:'Women Pink Floral Printed',
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    },
    {
        id:3,
        Product:'Women Pink Floral Printed',
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    },
    {
        id:4,
        Product:'Women Pink Floral Printed',
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    },
    {
        id:5,
        Product:'Women Pink Floral Printed',
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    },
    {
        id:6,
        Product:'Women Pink Floral Printed',
        Category:"Category : Fashion",
        Color:"Blue",
        Size: "Large",
        Quantity:"2",
        Price: "$59",
        Total: "189",
    }
    ]
    export { Customerdata};
    