const Productsdata = [
    {
        id: 1,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],
        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 2,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],
        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 3,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 4,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 5,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 6,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 7,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 8,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      },
      {
        id: 9,
        productName: "Women Pink Floral Printed",
        fashion:"Category : Fashion",
        price: "$49",
        category: "Palazzos",
        tags1: ["Jeans"],
        tags2: ["iPhone"],
        tags3: ["Laptops"],
        tags4: ["Mobiles"],
        tags5: ["Wallets"],        rating: 5.0,
        vendor: "Michle Shoes England",
        date: "Nov 12, 10:45 PM"
      }
]
export { Productsdata};
