const chatboxdata= [
    {
        id: 1,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Louis Litt',
        chatMessage: 'You just got LITT up, Mike.',
        chatTime: '9:51 AM',
        isActive: false,
      },
      {
        id:2,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Harvey Specter',
        chatMessage: 'Wrong. You take the gun....',
        chatTime: '4:32 PM',
        isActive: true,
      },
      {
        id:3,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Rachel Zane',
        chatMessage: 'I was thinking that we could...',
        chatTime: 'Wed',
        isActive: false,
      },
      {
        id:4,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Donna Paulsen',
        chatMessage: 'Mike, I know everything!',
        chatTime: 'Tue',
        isActive: false,
      },
      {
        id:5,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Jessica Pearson',
        chatMessage: 'Have you finished the draft...',
        chatTime: '9/3/2020',
        isActive: false,
      },
      {
        id:6,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Harold Gunderson',
        chatMessage: 'Thanks Mike! :)',
        chatTime: '12/3/2020',
        isActive: false,
      },
      {
        id:7,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Katrina Bennett',
        chatMessage: 'I\'ve sent you the files for...',
        chatTime: '16/3/2020',
        isActive: false,
      },
      {
        id:8,
        avatarUrl: 'https://placehold.co/110x110/png',
        chatTitle: 'Charles Forstman',
        chatMessage: 'Mike, this isn\'t over.',
        chatTime: '18/3/2020',
        isActive: false,
      },
      {
        id:9,
        avatarUrl: 'assets/images/avatars/11.png',
        chatTitle: 'Jonathan Sidwell',
        chatMessage: 'That\'s bullshit. This deal..',
        chatTime: '24/3/2020',
        isActive: false,
      },
]
export{chatboxdata}